server:
  port: 8081
  servlet.context-path: /cache-example

logging:
  level:
    root: info

spring:
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-wait: 10
        max-idle: 10
        min-idle: 10
    database: 0
  cache:
    type: redis
    redis:
      cache-null-values: false
      key-prefix: spring-cache
      time-to-live: 600
      use-key-prefix: true
